version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ./run.sh

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Monta o arquivo de configuração customizado do Nginx
    depends_on:
      - app